# Generated by Django 4.2.3 on 2023-07-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campsites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_phone', models.CharField(max_length=15)),
                ('facility_directions', models.CharField(max_length=500)),
                ('faciity_description', models.CharField(max_length=1000)),
                ('facility_map_url', models.CharField(max_length=500)),
            ],
        ),
    ]
