# Generated by Django 4.2.3 on 2023-07-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campsites',
            new_name='Campsite',
        ),
    ]
