# Generated by Django 4.2.3 on 2023-07-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsites', '0002_rename_campsites_campsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsite',
            old_name='faciity_description',
            new_name='facility_description',
        ),
    ]
