# Generated by Django 4.2.4 on 2023-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_address', models.CharField(max_length=200)),
                ('facility_phone', models.CharField(max_length=15)),
                ('facility_directions', models.CharField(max_length=500)),
                ('facility_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
